version: "3.8"
services:
  3s_front_end:
    build:
      context: .
      dockerfile: ./Dockerfile
    dtop_signal: SIGINT
    container_name: 3s_front_end
    image: 3s_front_end
    ports:
      - "127.0.0.1:8000:2020"
    volume:
      - .:/app
    restart: always
